name: triplespec_focus
dependencies:
  - python="3.10"
  - astropy
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - pip:
      - ccdproc
      - coveralls
      - photutils>=1.4.0
      - sphinx_rtd_theme
      - sphinx
